"""rename tables

Revision ID: 167444262f90
Revises: 2940a899207a
Create Date: 2023-07-24 04:44:33.296149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167444262f90'
down_revision = '2940a899207a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_fiat', sa.DECIMAL(), nullable=False))
    op.add_column('orders', sa.Column('worker_fiat', sa.DECIMAL(), nullable=False))
    op.add_column('orders', sa.Column('profit_fiat', sa.DECIMAL(), nullable=False))
    op.drop_column('orders', 'fiat_client')
    op.drop_column('orders', 'fiat_worker')
    op.drop_column('orders', 'fiat_profit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fiat_profit', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('fiat_worker', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('fiat_client', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'profit_fiat')
    op.drop_column('orders', 'worker_fiat')
    op.drop_column('orders', 'client_fiat')
    # ### end Alembic commands ###
