"""rename tables

Revision ID: 224e4b220786
Revises: e3ceb3be941c
Create Date: 2023-07-24 05:44:37.179500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224e4b220786'
down_revision = 'e3ceb3be941c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
