"""a

Revision ID: 25979ee1e026
Revises: 4ffdd6f8c781
Create Date: 2023-07-21 07:40:39.392267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25979ee1e026'
down_revision = '4ffdd6f8c781'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_accounts', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('crypto_accounts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('crypto_accounts', 'jwt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('crypto_accounts', 'private_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('crypto_accounts', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workers', 'wallet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'wallet',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('crypto_accounts', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('crypto_accounts', 'private_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('crypto_accounts', 'jwt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('crypto_accounts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('crypto_accounts', 'status')
    # ### end Alembic commands ###
