"""rename tables

Revision ID: 2940a899207a
Revises: 27aa66feb324
Create Date: 2023-07-24 04:42:50.368265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2940a899207a'
down_revision = '27aa66feb324'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fiat_client', sa.DECIMAL(), nullable=False))
    op.add_column('orders', sa.Column('fiat_worker', sa.DECIMAL(), nullable=False))
    op.add_column('orders', sa.Column('fiat_profit', sa.DECIMAL(), nullable=False))
    op.drop_column('orders', 'fiat_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fiat_value', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'fiat_profit')
    op.drop_column('orders', 'fiat_worker')
    op.drop_column('orders', 'fiat_client')
    # ### end Alembic commands ###
