"""init db

Revision ID: 4ffdd6f8c781
Revises: 
Create Date: 2023-07-21 04:53:11.997724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffdd6f8c781'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('crypto_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('jwt', sa.String(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('moderator_id', sa.String(), nullable=False),
    sa.Column('moderator_name', sa.String(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_username', sa.String(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('coin_value', sa.DECIMAL(), nullable=False),
    sa.Column('course', sa.DECIMAL(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_account', sa.String(), nullable=False),
    sa.Column('fiat_value', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('moderator_id', sa.String(), nullable=True),
    sa.Column('crypto_account', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('general_status', sa.String(), nullable=False),
    sa.Column('sber_status', sa.String(), nullable=False),
    sa.Column('tinkoff_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    op.drop_table('transactions')
    op.drop_table('tickets')
    op.drop_table('crypto_accounts')
    op.drop_table('clients')
    # ### end Alembic commands ###
