"""a

Revision ID: 555cab92387a
Revises: 25979ee1e026
Create Date: 2023-07-21 11:11:04.457534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555cab92387a'
down_revision = '25979ee1e026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_accounts', sa.Column('processes', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('dtime', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    op.add_column('transactions', sa.Column('dtime', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'dtime')
    op.drop_column('tickets', 'dtime')
    op.drop_column('crypto_accounts', 'processes')
    # ### end Alembic commands ###
