"""a

Revision ID: 5ec4eed9d671
Revises: 224e4b220786
Create Date: 2023-07-25 02:05:20.153896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec4eed9d671'
down_revision = '224e4b220786'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('refuse_comments', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'refuse_comments')
    # ### end Alembic commands ###
