"""rename tables

Revision ID: e4fbb6becdb4
Revises: 167444262f90
Create Date: 2023-07-24 05:37:24.332046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4fbb6becdb4'
down_revision = '167444262f90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'coin_value')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'client_fiat')
    op.drop_column('orders', 'profit_fiat')
    op.drop_column('orders', 'worker_fiat')
    op.drop_column('workers', 'total_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('total_month', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('worker_fiat', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('profit_fiat', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('client_fiat', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('currency', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('coin_value', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
